apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: movie-db
spec:
  serviceName: "movie-db"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
      - name: movie-db
        image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
        ports:
        - containerPort: {{ .Values.db.service.port }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.db.user }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-movie-password-secret
              key: password
        - name: POSTGRES_DB
          value: {{ .Values.db.name }}
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

